language: php

php:
    - 5.4
    - 5.5
    - 5.6
    - hhvm

before_script:
    - npm install -g bower
    - bower install
    - composer self-update
    - composer install --prefer-source --no-interaction --dev

script: vendor/bin/codecept

matrix:
    fast_finish: true
    allow_failures:
        - php: hhvm

notifications:
    on_success: never
    on_failure: always
