language: php

php:
  - 5.4
  - 5.5
  - 5.6
  - hhvm

before_script:
  - npm install -g bower
  - bower install
  - composer self-update
  - composer install --prefer-source --no-interaction
  - psql -c 'create database travis_ci_test;' -U postgres
  - psql -c "CREATE USER homestead WITH PASSWORD 'secret';" -U postgres
  - php artisan migrate:refresh --seed -n
  - ./vendor/bin/codecept build

script:
  - ./vendor/bin/codecept run

matrix:
    fast_finish: true
    allow_failures:
        - php: hhvm

notifications:
    on_success: never
    on_failure: always
